# Generated by Django 6.0.1 on 2026-02-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
